---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAvoCWlpZZFCKEhFWiVEVGCzP0JYiioh4gB+QwOI8x5jBjyyaW9BSiDei7vVphOZnXEwY5GJOsiCWr/N3jnAh0pju5j+2KE8wx8+7wn/LGtchtG3DsH2/anEyio3k1r0ifLRUZjDrNuSlwgDtjtVrb9PNX3Ds3UHswTlOYrt0oLthWxoCATTlAi0WdkXdP7CQjANABhZvGl4EBsIR57Gc2HJgk3xrA1nM0JSsRLOrlWDTEzhluffzckCWRvWsuZDJc0ampxGdyPTlim90zwQhDztspYfU4hWjUwJWazaT/BJPC6lQ60OdMMtxKL12t4FMwNiKr3JNbRifDmSg2gnDa99uLh5MyWusl74zaej7LykcN9i0TUX3HYwoRc2Mom0uXr/+mZpZmIHayGkrLnVIGoLKEEU9NB8txBrUj3HVnAIxyRucFatBi8iZuOmQukKJNnFe6ByKRpmg2rLKTbFByzPj5mjosUuOaroACwWymzC23wDadiR5rXApDbgQ5tWWNMl8qNik0MHlwRPVw5wXOmqxl0EjENw0a2RmB66Q1rY7fFykgjTzCAIxOK57wMhNmXXtr2i6spsIRszl44LCbLxWlBPirTjqxBH87bMWMijcmxo5r7E6lwUTje1oR38a2XCqqi2yFHBwgJ8J1rBrJTy/IJn8qFe27hrBf0dcYzUcmcgpp+QghSzzNuF5zItw7Yty+suZ3Hd15CN2flLisFE3BRcYGWotKN878cjha50dTPDaxc6jOwaStMaoimAQtf544=
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
