---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: api-keys
  namespace: default
spec:
  encryptedData:
    APIKEY: AgAE7qeQq+ken5bJ6ICDue9YFpbSLUslsGHylom4IjhNSJe+paWVo2qWLp1NHlV2hGymRJjzobsXpKE57EVgC0jLfMqas+6Roprx3Q2I0Y/3w9ZCByIkBiePJ6vEg4bN3JzhNw/rna8XEMZ0yoWfE4dqpvYJH2mwIuFMCS0Rge71r+ffoNliR6cOYhjXJU3lf1j/8a0NcPX4WGD01oOe/zw+G9dW5EdMvtO1J6okHr/1veUB4qC+vAb3pMYK5AvZZ8HCRacYkAX1+smtCXhm78VQTBnE0aH0nXKD17Q2gZMEDAzINExMGTww6ai1qRnd7UPbMHdu/KI68LwHeO7KeUzDmLLIqmiYA+k8+LFd5JLRYxWJVkQV8ib80m7S4796h8BrseMjmBD4E4P0HqSPl7hzPZCuRSCMY95YXFdLRZDmyYMPcwKTWEBwsJXKAm2yZh1NKWwJGyZq4j1tFP5PJMRvWSlkHSOPkPOj+BWIlnkBh7/VLL0IFENWVzgBUqZowuVErpy5/Z7CSQOhQ4/fjHIcxtbAXMsydtH3IA4OHjCFCuXaCavmCDj/z/n4M3jqatYY3zoMGoGSU+QJ0NiTSmt0CARc8AeZve/rft7b0ROk1ZWRYZui8q61zuWacq57eIPjHNxYStxqIjI3Urm4AVnj5QaNcbjmNbQO67Sde13HwutSJDJPb8bgc3NMGPS92/6yHOBToFIywDIxBWSoIXRKHGF1YoRdcaafNIzE5QJeTQVTdzEMK3RDW7dqSdusX+KgFg==
  template:
    metadata:
      creationTimestamp: null
      name: api-keys
      namespace: default
    type: Opaque
